name: xitfarge
options:
  bundleIdPrefix: com.xitfarge
  deploymentTarget:
    iOS: "14.0"
  xcodeVersion: "15.4"
generateEmptyDirectories: true

targets:
  xitfarge:
    type: application
    platform: iOS
    sources:
      - path: MiApp
    settings:
      base:
        INFOPLIST_FILE: MiApp/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.xitfarge.app
        PRODUCT_NAME: xitfarge
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: NO
        TARGETED_DEVICE_FAMILY: "1,2"
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"
    scheme:
      testTargets: []
